// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ck/internal/biz"
	"ck/internal/conf"
	"ck/internal/data"
	"ck/internal/server"
	"ck/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	producer := data.NewRocketMQProducer(confData)
	pushConsumer := data.NewRocketMQConsumer(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db, client, producer, pushConsumer)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	cronService := service.NewCronService(confData, logger)
	app := newApp(logger, grpcServer, httpServer, cronService)
	return app, func() {
		cleanup()
	}, nil
}
