// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDwdOrder = "dwd_orders"

// DwdOrder DWDå±‚è®¢å•è¡¨-å·²å®Œæˆè®¢å•
type DwdOrder struct {
	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID   string     `gorm:"column:order_id;not null;comment:è®¢å•ID" json:"order_id"`                          // è®¢å•ID
	Detail    string     `gorm:"column:detail;not null;comment:è®¢å•è¯¦æƒ…JSON" json:"detail"`                      // è®¢å•è¯¦æƒ…JSON
	CreatedAt *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:åˆ›å»ºæ—¶é—´" json:"created_at"` // åˆ›å»ºæ—¶é—´
	UpdatedAt *time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:æ›´æ–°æ—¶é—´" json:"updated_at"` // æ›´æ–°æ—¶é—´
}

// TableName DwdOrder's table name
func (*DwdOrder) TableName() string {
	return TableNameDwdOrder
}
