// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDwsOrder = "dws_orders"

// DwsOrder DWS Orders Table - Data Warehouse Service Layer
type DwsOrder struct {
	ID              int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID         string     `gorm:"column:order_id;not null" json:"order_id"`
	CustomerID      *int64     `gorm:"column:customer_id" json:"customer_id"`
	OrderAmount     *float64   `gorm:"column:order_amount" json:"order_amount"`
	OrderStatus     *string    `gorm:"column:order_status" json:"order_status"`
	OrderDate       *time.Time `gorm:"column:order_date" json:"order_date"`
	PaymentMethod   *string    `gorm:"column:payment_method" json:"payment_method"`
	ShippingAddress *string    `gorm:"column:shipping_address" json:"shipping_address"`
	PushStatus      *string    `gorm:"column:push_status;default:pending;comment:pending, pushed, failed" json:"push_status"` // pending, pushed, failed
	CreatedAt       *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       *time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName DwsOrder's table name
func (*DwsOrder) TableName() string {
	return TableNameDwsOrder
}
