// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOdsOrder = "ods_orders"

// OdsOrder ODSå±‚è®¢å•è¡¨
type OdsOrder struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:è‡ªå¢žID" json:"id"`                          // è‡ªå¢žID
	OrderID   int64     `gorm:"column:order_id;not null;comment:è®¢å•ID" json:"order_id"`                                   // è®¢å•ID
	Detail    string    `gorm:"column:detail;not null;comment:è®¢å•è¯¦æƒ…JSON" json:"detail"`                               // è®¢å•è¯¦æƒ…JSON
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:åˆ›å»ºæ—¶é—´" json:"created_at"` // åˆ›å»ºæ—¶é—´
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:æ›´æ–°æ—¶é—´" json:"updated_at"` // æ›´æ–°æ—¶é—´
}

// TableName OdsOrder's table name
func (*OdsOrder) TableName() string {
	return TableNameOdsOrder
}
